baseURL = "https://www.johnfalsettomusic.com/"
languageCode = "en-us"
title = "John Falsetto Pfumojena"
theme = "jp"
pluralizelisttitles = false

[permalinks]
    page = "/:slug/"

[menu]
    [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10

    [[menu.main]]
    name = "Events"
    url = "/event/"
    weight = 50

    [[menu.main]]
    name = "Theatre"
    url = "#"
    weight = 30

    [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 20

    [[menu.main]]
    name = "Photos"
    url = "#"
    weight = 40

    [[menu.main]]
    name = "Store"
    url = "#"
    weight = 60

    [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 70

    [[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/johnfalsetto/"
    pre = "/static/icons/instagram.svg"
    weight = 30

    [[menu.social]]
    name = "Facebook"
    url = "https://www.facebook.com/falsettojohn"
    pre = "/static/icons/facebook.svg"
    weight = 10

    [[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/falsettojohn"
    pre = "/static/icons/twitter.svg"
    weight = 20

    [[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCqtUvPIB4P6qh8TChfgBCVQ"
    pre = "/static/icons/youtube.svg"
    weight = 50

    [[menu.social]]
    name = "Spotlight"
    url = "https://www.spotlight.com/interactive/cv/2850-8941-5930"
    pre = "/static/icons/spotlight.svg"
    weight = 40


    [[menu.sharing]]
    name = "Share via Facebook"
    url = "https://www.facebook.com/sharer/sharer.php?u=shareurl"
    pre = "/static/icons/facebook.svg"
    weight = "10"

    [[menu.sharing]]
    name = "Share via Twitter"
    url = "https://twitter.com/intent/tweet?url=shareurl&text=title"
    pre = "/static/icons/twitter.svg"
    weight = "20"

    [[menu.sharing]]
    name = "Share via WhatsApp"
    url = "https://web.whatsapp.com/send?text=title%20shareurl"
    pre = "/static/icons/whatsapp.svg"
    weight = "30"
    
    [[menu.sharing]]
    name = "Email"
    url = "mailto:?subject=title&body=title%20shareurl"
    pre = "/static/icons/email.svg"
    weight = "40"