# file ./softwareengineering/.github/workflow/deploy.yml

name: "deploy website"

on:
  push:
    branches:
      - master

jobs:
  job_deploy_website:
    name: "deploy website"
    runs-on: ubuntu-latest
    steps:
      - name: "Installing hugo"
        run: |
          cd ~
          wget https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Linux-64bit.deb
          sudo dpkg -i hugo*.deb
          hugo version
      - name: "add keys"
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - uses: actions/checkout@v1
      - name: "checkout"
        run: |
          git submodule sync --recursive
          git submodule update --recursive --init
          cd public
          git checkout master
          cd ..
      - name: "compiling website"
        run: hugo
